### ISSUE TITLE
splitting produces weird error message 

### ISSUE THREAD

**Issue by marcinjurek** [marcinjurek/pyMRA#6]
for:
```python
dim_x=100
M=3, J=4, r=4
```
the following message is displayed
```console
Traceback (most recent call last):
  File "test-MRD-row-order.py", line 51, in <module>
    mrd = MRD(locs, M, J, r0, critDepth, covExp)
  File "../MRA/MRD.py", line 30, in __init__
    self.root = Node(None, 'r', locs, locs, M, J, r, critDepth, cov)
  File "../MRA/MRDNode.py", line 74, in __init__
    newChild = Node(self, chID, chLocs, chNotKnots, levelsFromLeaves-1, J, r, critDepth, covCh)
  File "../MRA/MRDNode.py", line 74, in __init__
    newChild = Node(self, chID, chLocs, chNotKnots, levelsFromLeaves-1, J, r, critDepth, covCh)
  File "../MRA/MRDNode.py", line 45, in __init__
    splits = self._getJSplits(J, newNotKnots)
  File "../MRA/MRDNode.py", line 192, in _getJSplits
    kmeans = KMeans(n_clusters=J, random_state=0).fit(notKnots)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/cluster/k_means_.py", line 880, in fit
    X = self._check_fit_data(X)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/cluster/k_means_.py", line 857, in _check_fit_data
    X.shape[0], self.n_clusters))
ValueError: n_samples=2 should be >= n_clusters=4
```

**Comment by marcinjurek** [comment]
So we have a different error right now:
```python
12:05:02 === simulating data ===
12:05:02 simulating locations
12:05:02 calculating covariance matrix
12:05:02 simulating observations
12:05:02 === starting MRA ===
3
Traceback (most recent call last):
  File "test-MRA.py", line 111, in <module>
    mraTree = MRATree(locs, r0, cov, y_obs, R, M=M, J=J)
  File "../../pyMRA/MRATree.py", line 43, in __init__
    self.root = Node(None, 'r', locs, locs, self.M, self.J, self.r, critDepth, cov, obsM, R)
  File "../../pyMRA/MRANode.py", line 89, in __init__
    newChild = Node(self, chID, chLocs, chNotKnots, levelsFromLeaves-1, J, r, critDepth, covCh, chObs, chR)
  File "../../pyMRA/MRANode.py", line 89, in __init__
    newChild = Node(self, chID, chLocs, chNotKnots, levelsFromLeaves-1, J, r, critDepth, covCh, chObs, chR)
  File "../../pyMRA/MRANode.py", line 89, in __init__
    newChild = Node(self, chID, chLocs, chNotKnots, levelsFromLeaves-1, J, r, critDepth, covCh, chObs, chR)
  File "../../pyMRA/MRANode.py", line 39, in __init__
    self.kInds = np.arange(self.N)[np.flatnonzero(npi.contains(notKnots, self.locs))]          
  File "/usr/local/lib/python3.5/dist-packages/numpy_indexed/arraysetops.py", line 73, in contains
    this = as_index(this, axis=axis, lex_as_struct=True, base=True)
  File "/usr/local/lib/python3.5/dist-packages/numpy_indexed/index.py", line 327, in as_index
    return ObjectIndex(keys, axis, stable=stable)
  File "/usr/local/lib/python3.5/dist-packages/numpy_indexed/index.py", line 179, in __init__
    keys = array_as_object(keys)
  File "/usr/local/lib/python3.5/dist-packages/numpy_indexed/utility.py", line 100, in array_as_object
    arr = arr.reshape(len(arr), -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
```

**Comment by marcinjurek** [comment]
Here is the problem. Sometimes, especially when we have a lot of basis functions at each resolution, deep down the hierarchy there isn't enough "free" grid points to designate as knots (i.e. `len(newNotKnots<J`). We try to address this problem with two fixes: 
- when we split the `notKnots` in the `_getJSplits` function we make sure that each subdomain has at least one point. This has been copied from the MRF repository.
- we also split into `minJ = min(J, len(newNotKnots)` rather than into `J` subregions. This guarantees that each region has at least one "free" grid point
This seems to work for the `dim_x=100; dim_y=100` case in the sense that the MRA tree has been built alright. But then the function that creates the `B` matrix produced the following error:
```
Traceback (most recent call last):
  File "test-MRA.py", line 127, in <module>
    B = mraTree.getBasisFunctionsMatrix(distr="prior")
  File "../../pyMRA/MRATree.py", line 476, in getBasisFunctionsMatrix
    B = np.hstack((B, Bm))
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/shape_base.py", line 293, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

**Comment by marcinjurek** [comment]
So it is pretty hard to debug this problem with 10000 grid points. For the `dim_x=100; J=4; r=2; M=3` case the following is happening:
```console
Traceback (most recent call last):
  File "test-MRA.py", line 111, in <module>
    mraTree = MRATree(locs, r0, cov, y_obs, R, J=J, M=M)
  File "../../pyMRA/MRATree.py", line 44, in __init__
    self.root = Node(None, 'r', locs, locs, self.M, self.J, self.r, critDepth, cov, obsM, R)
  File "../../pyMRA/MRANode.py", line 92, in __init__
    newChild = Node(self, chID, chLocs, chNotKnots, levelsFromLeaves-1, J, r, critDepth, covCh, chObs, chR)
  File "../../pyMRA/MRANode.py", line 92, in __init__
    newChild = Node(self, chID, chLocs, chNotKnots, levelsFromLeaves-1, J, r, critDepth, covCh, chObs, chR)
  File "../../pyMRA/MRANode.py", line 101, in __init__
    self.calculatePosterior(obs, R)
  File "../../pyMRA/MRANode.py", line 493, in calculatePosterior
    self.BTil[k][chInds,:] = ch.BTil[k] - ch.BTil[ch.res] * ch.kTil * ch.A[ch.res][k]
ValueError: shape mismatch: value array of shape (3,4) could not be broadcast to indexing result of shape (3,3)
```

**Comment by marcinjurek** [comment]
This problem is pretty a pretty complicated one to solve. It is all about finding the maximum number of resolutions we can use. One approach is to ensure that every leaf has at least grid point. This might result in some leaves effectively not having any "unused" grid points. That's because the splits aren't always optimal. For example if we have 17 points and J=4 then we would "optimally" split into 5, 4, 4, 4. But maybe for some reason we ended up splitting into 5, 5, 3, 4. This gets even more complicated if we split on multiple levels. 
Another approach is to ensure that at each level we have at least r knots. This means that leaves will generally have more than r knots. But this will also not work for 1-RF because over there we specifically want each region to have exactly 1 knot at the finest level. For know we adopt the second strategy for general MRA
