### ISSUE TITLE
some errors encountered in the edge case of knot assignment

### ISSUE THREAD

**Issue by marcinjurek** [marcinjurek/pyMRA#8]
When:
```python
dim_x = 100
M=1; r0=10; J=dim_x-r0
```
the code crashes
```console
Traceback (most recent call last):
  File "test-MRA.py", line 111, in <module>
    mraTree = MRATree(locs, M, J, r0, critDepth, cov, y_obs, R)
  File "/home/marcin/.local/lib/python3.5/site-packages/pyMRA/MRATree.py", line 31, in __init__
    self.root = Node(None, 'r', locs, locs, M, J, r, critDepth, cov, obsM, R)
  File "/home/marcin/.local/lib/python3.5/site-packages/pyMRA/MRANode.py", line 84, in __init__
    newChild = Node(self, chID, chLocs, chNotKnots, levelsFromLeaves-1, J, r, critDepth, covCh, chObs, chR)
  File "/home/marcin/.local/lib/python3.5/site-packages/pyMRA/MRANode.py", line 36, in __init__
    self.kInds = np.arange(self.N)[np.flatnonzero(npi.contains(notKnots, self.locs))]          
  File "/usr/local/lib/python3.5/dist-packages/numpy_indexed/arraysetops.py", line 73, in contains
    this = as_index(this, axis=axis, lex_as_struct=True, base=True)
  File "/usr/local/lib/python3.5/dist-packages/numpy_indexed/index.py", line 327, in as_index
    return ObjectIndex(keys, axis, stable=stable)
  File "/usr/local/lib/python3.5/dist-packages/numpy_indexed/index.py", line 179, in __init__
    keys = array_as_object(keys)
  File "/usr/local/lib/python3.5/dist-packages/numpy_indexed/utility.py", line 100, in array_as_object
    arr = arr.reshape(len(arr), -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
```
This might have to do with how the knots are assigned in the MRANode._getJSplits function. See the MRDNode.py file in the MRF repo

**Comment by marcinjurek** [comment]
this is related to #6 and #11 . Thoughts on this topic so far are captured in this little memo
[choosing-M.pdf](https://github.com/marcinjurek/pyMRA/files/1789521/choosing-M.pdf)

**Comment by marcinjurek** [comment]
adopted the solution described in the memo. Closing the issue for now.
